-- MySQL Script generated by MySQL Workbench
-- Sun Jan 21 02:47:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_BiBLIOTECA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD_BiBLIOTECA` ;

-- -----------------------------------------------------
-- Schema BD_BiBLIOTECA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_BiBLIOTECA` DEFAULT CHARACTER SET utf8 ;
USE `BD_BiBLIOTECA` ;

-- -----------------------------------------------------
-- Table `BD_BiBLIOTECA`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_BiBLIOTECA`.`Autor` ;

CREATE TABLE IF NOT EXISTS `BD_BiBLIOTECA`.`Autor` (
  `idAutor` VARCHAR(6) NOT NULL,
  `autor_nombre` VARCHAR(40) NOT NULL,
  `autor_apellido` VARCHAR(40) NOT NULL,
  `autor_nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_BiBLIOTECA`.`Editorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_BiBLIOTECA`.`Editorial` ;

CREATE TABLE IF NOT EXISTS `BD_BiBLIOTECA`.`Editorial` (
  `idEditorial` VARCHAR(6) NOT NULL,
  `ed_nombre` VARCHAR(50) NOT NULL,
  `ed_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEditorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_BiBLIOTECA`.`Genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_BiBLIOTECA`.`Genero` ;

CREATE TABLE IF NOT EXISTS `BD_BiBLIOTECA`.`Genero` (
  `idGenero` VARCHAR(6) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_BiBLIOTECA`.`Idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_BiBLIOTECA`.`Idioma` ;

CREATE TABLE IF NOT EXISTS `BD_BiBLIOTECA`.`Idioma` (
  `idIdioma` VARCHAR(6) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIdioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_BiBLIOTECA`.`Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_BiBLIOTECA`.`Libro` ;

CREATE TABLE IF NOT EXISTS `BD_BiBLIOTECA`.`Libro` (
  `idLibro` VARCHAR(6) NOT NULL,
  `lib_titulo` VARCHAR(50) NOT NULL,
  `lib_autor` VARCHAR(6) NOT NULL,
  `lib_editorial` VARCHAR(6) NOT NULL,
  `lib_fecpub` DATE NOT NULL,
  `lib_genero` VARCHAR(6) NOT NULL,
  `lib_paginas` INT NOT NULL,
  `lib_cantidad` INT NOT NULL,
  `lib_idioma` VARCHAR(6) NOT NULL,
  `lib_estado` INT NOT NULL,
  PRIMARY KEY (`idLibro`),
  INDEX `lib_autor_idx` (`lib_autor` ASC),
  INDEX `lib_editorial_idx` (`lib_editorial` ASC),
  INDEX `lib_genero_idx` (`lib_genero` ASC),
  INDEX `lib_idioma_idx` (`lib_idioma` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_BiBLIOTECA`.`Trabajador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_BiBLIOTECA`.`Trabajador` ;

CREATE TABLE IF NOT EXISTS `BD_BiBLIOTECA`.`Trabajador` (
  `idTrabajador` VARCHAR(6) NOT NULL,
  `trab_pass` VARCHAR(10) NOT NULL,
  `trab_nombre` VARCHAR(40) NOT NULL,
  `trab_apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTrabajador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_BiBLIOTECA`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_BiBLIOTECA`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `BD_BiBLIOTECA`.`Usuario` (
  `idUsuario` VARCHAR(8) NOT NULL,
  `usu_nombre` VARCHAR(45) NOT NULL,
  `usu_apellido` VARCHAR(45) NOT NULL,
  `usu_direccion` VARCHAR(100) NOT NULL,
  `usu_telefono` VARCHAR(9) NOT NULL,
  `usu_contraseña` VARCHAR(10) NOT NULL,
  `usu_estado` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_BiBLIOTECA`.`Registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD_BiBLIOTECA`.`Registro` ;

CREATE TABLE IF NOT EXISTS `BD_BiBLIOTECA`.`Registro` (
  `idRegistro` INT NOT NULL AUTO_INCREMENT,
  `idusuario` VARCHAR(8) NOT NULL,
  `idlibro` VARCHAR(6) NOT NULL,
  `reg_horareserva` DATETIME NOT NULL,
  `reg_horadevolucion` DATETIME NULL,
  PRIMARY KEY (`idRegistro`),
  INDEX `idusuario_idx` (`idusuario` ASC),
  INDEX `idlibro_idx` (`idlibro` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BD_BiBLIOTECA`.`Autor`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_BiBLIOTECA`;
INSERT INTO `BD_BiBLIOTECA`.`Autor` (`idAutor`, `autor_nombre`, `autor_apellido`, `autor_nacionalidad`) VALUES ('A00001', 'Rafael', 'Abella', 'España');
INSERT INTO `BD_BiBLIOTECA`.`Autor` (`idAutor`, `autor_nombre`, `autor_apellido`, `autor_nacionalidad`) VALUES ('A00002', 'Lisa', 'Abbend', 'España');
INSERT INTO `BD_BiBLIOTECA`.`Autor` (`idAutor`, `autor_nombre`, `autor_apellido`, `autor_nacionalidad`) VALUES ('A00003', 'Martin', 'Allen', 'España');
INSERT INTO `BD_BiBLIOTECA`.`Autor` (`idAutor`, `autor_nombre`, `autor_apellido`, `autor_nacionalidad`) VALUES ('A00004', 'Ciro', 'Alegria', 'Peru');
INSERT INTO `BD_BiBLIOTECA`.`Autor` (`idAutor`, `autor_nombre`, `autor_apellido`, `autor_nacionalidad`) VALUES ('A00005', 'Cesar', 'Vallejo', 'Peru');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BD_BiBLIOTECA`.`Editorial`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_BiBLIOTECA`;
INSERT INTO `BD_BiBLIOTECA`.`Editorial` (`idEditorial`, `ed_nombre`, `ed_pais`) VALUES ('E00001', 'Anaya', 'España');
INSERT INTO `BD_BiBLIOTECA`.`Editorial` (`idEditorial`, `ed_nombre`, `ed_pais`) VALUES ('E00002', 'Norma', 'Peru');
INSERT INTO `BD_BiBLIOTECA`.`Editorial` (`idEditorial`, `ed_nombre`, `ed_pais`) VALUES ('E00003', 'Santillana', 'Peru');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BD_BiBLIOTECA`.`Genero`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_BiBLIOTECA`;
INSERT INTO `BD_BiBLIOTECA`.`Genero` (`idGenero`, `genero`) VALUES ('G00001', 'Terror');
INSERT INTO `BD_BiBLIOTECA`.`Genero` (`idGenero`, `genero`) VALUES ('G00002', 'Aventura');
INSERT INTO `BD_BiBLIOTECA`.`Genero` (`idGenero`, `genero`) VALUES ('G00003', 'Autoayuda');
INSERT INTO `BD_BiBLIOTECA`.`Genero` (`idGenero`, `genero`) VALUES ('G00004', 'Poesia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BD_BiBLIOTECA`.`Idioma`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_BiBLIOTECA`;
INSERT INTO `BD_BiBLIOTECA`.`Idioma` (`idIdioma`, `idioma`) VALUES ('I00001', 'Español');
INSERT INTO `BD_BiBLIOTECA`.`Idioma` (`idIdioma`, `idioma`) VALUES ('I00002', 'Ingles');
INSERT INTO `BD_BiBLIOTECA`.`Idioma` (`idIdioma`, `idioma`) VALUES ('I00003', 'Japones');
INSERT INTO `BD_BiBLIOTECA`.`Idioma` (`idIdioma`, `idioma`) VALUES ('I00004', 'Chino');
INSERT INTO `BD_BiBLIOTECA`.`Idioma` (`idIdioma`, `idioma`) VALUES ('I00005', 'Aleman');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BD_BiBLIOTECA`.`Libro`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_BiBLIOTECA`;
INSERT INTO `BD_BiBLIOTECA`.`Libro` (`idLibro`, `lib_titulo`, `lib_autor`, `lib_editorial`, `lib_fecpub`, `lib_genero`, `lib_paginas`, `lib_cantidad`, `lib_idioma`, `lib_estado`) VALUES ('L00001', 'El mundo es ancho y ajeno', 'A00004', 'E00001', '1990/10/20', 'G00001', 200, 1, 'I00001', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BD_BiBLIOTECA`.`Trabajador`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_BiBLIOTECA`;
INSERT INTO `BD_BiBLIOTECA`.`Trabajador` (`idTrabajador`, `trab_pass`, `trab_nombre`, `trab_apellido`) VALUES ('T10001', '123456', 'Daniel', 'Romero');
INSERT INTO `BD_BiBLIOTECA`.`Trabajador` (`idTrabajador`, `trab_pass`, `trab_nombre`, `trab_apellido`) VALUES ('T20001', '123456', 'Irene', 'Cruz');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BD_BiBLIOTECA`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `BD_BiBLIOTECA`;
INSERT INTO `BD_BiBLIOTECA`.`Usuario` (`idUsuario`, `usu_nombre`, `usu_apellido`, `usu_direccion`, `usu_telefono`, `usu_contraseña`, `usu_estado`) VALUES ('72696054', 'Daniel', 'Romero', 'Calle Jose de san Martin 624 Urb Sn Rafael', '934431081', '123456', 1);
INSERT INTO `BD_BiBLIOTECA`.`Usuario` (`idUsuario`, `usu_nombre`, `usu_apellido`, `usu_direccion`, `usu_telefono`, `usu_contraseña`, `usu_estado`) VALUES ('72696542', 'Jose', 'Perales', 'Calle Bernardo Alcedo 208', '946515284', '123456', 1);

COMMIT;

